### ISSUE TITLE
'model.py' Function Requires Modification to Return Values Instead of Printing

### ISSUE THREAD

**Issue by MajorTimberWolf** [MajorTimberWolf/bc-git#2]
## Description

The current implementation in 'model.py' relies on a print statement within a function, resulting in inconsistent behavior. To ensure proper functionality and consistency, it is recommended to replace the print statement with a return statement.

## Steps to Reproduce

1. Execute the 'model.py' script.
2. Observe the behavior when the function containing the print statement is called.

## Expected Behavior

The 'model.py' script should consistently operate as intended without any unexpected outputs.

## Current Behavior

Inconsistencies arise when the function with the print statement is called, impacting the overall behavior of the script.

## Proposed Solution

Replace the print statement with a return statement in the relevant function within 'model.py' to achieve a more predictable and consistent behavior.

**Comment by NinjaNeku** [comment]
#9 fix: replace print to return
